-- Migration: Optimize audit triggers
-- Keep audit ONLY on clientes and ficha_anamnese_capilar
-- Remove audit triggers from all other tables

-- ============================================================
-- 1. DROP audit triggers from non-critical tables
-- ============================================================

-- agendamentos
DROP TRIGGER IF EXISTS trg_agendamentos_capture_row_change ON agendamentos;

-- client_photos
DROP TRIGGER IF EXISTS trg_client_photos_capture_row_change ON client_photos;

-- clinic_preferences
DROP TRIGGER IF EXISTS trg_clinic_preferences_capture_row_change ON clinic_preferences;

-- company_document_folders
DROP TRIGGER IF EXISTS trg_company_document_folders_capture_row_change ON company_document_folders;

-- company_documents
DROP TRIGGER IF EXISTS trg_company_documents_capture_row_change ON company_documents;

-- diagnostico_capilar
DROP TRIGGER IF EXISTS trg_diagnostico_capilar_capture_row_change ON diagnostico_capilar;

-- historico_procedimentos
DROP TRIGGER IF EXISTS trg_historico_procedimentos_capture_row_change ON historico_procedimentos;

-- manutencao_homecare
DROP TRIGGER IF EXISTS trg_manutencao_homecare_capture_row_change ON manutencao_homecare;

-- pre_consulta_envios
DROP TRIGGER IF EXISTS trg_pre_consulta_envios_capture_row_change ON pre_consulta_envios;

-- services
DROP TRIGGER IF EXISTS trg_services_capture_row_change ON services;

-- ============================================================
-- 2. VERIFY remaining audit triggers (should be only clientes + ficha_anamnese_capilar)
-- ============================================================

DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT DISTINCT event_object_table
    FROM information_schema.triggers
    WHERE trigger_name LIKE '%capture_row_change%'
      AND event_object_schema = 'public'
  LOOP
    RAISE NOTICE 'Audit still active on table: %', r.event_object_table;
  END LOOP;
END $$;

-- ============================================================
-- 3. Archive old audit rows from removed tables into a history table
-- ============================================================

CREATE TABLE IF NOT EXISTS private.row_change_audit_archive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_schema TEXT NOT NULL,
  table_name TEXT NOT NULL,
  operation TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
  record_identity JSONB DEFAULT '{}'::jsonb,
  changed_at TIMESTAMPTZ DEFAULT NOW(),
  jwt_subject TEXT,
  jwt_role TEXT,
  db_role TEXT DEFAULT CURRENT_USER,
  transaction_id BIGINT DEFAULT txid_current(),
  old_record JSONB,
  new_record JSONB,
  archived_at TIMESTAMPTZ DEFAULT NOW()
);

-- Move existing audit rows from non-critical tables to archive
INSERT INTO private.row_change_audit_archive (
  table_schema, table_name, operation, record_identity,
  changed_at, jwt_subject, jwt_role, db_role, transaction_id,
  old_record, new_record
)
SELECT
  table_schema, table_name, operation, record_identity,
  changed_at, jwt_subject, jwt_role, db_role, transaction_id,
  old_record, new_record
FROM private.row_change_audit
WHERE table_name NOT IN ('clientes', 'ficha_anamnese_capilar');

-- Delete archived rows from the main audit table
DELETE FROM private.row_change_audit
WHERE table_name NOT IN ('clientes', 'ficha_anamnese_capilar');
