CREATE SCHEMA IF NOT EXISTS private;

REVOKE ALL ON SCHEMA private FROM PUBLIC;
REVOKE ALL ON SCHEMA private FROM anon;
GRANT USAGE ON SCHEMA private TO authenticated;

CREATE TABLE IF NOT EXISTS private.row_change_audit (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	table_schema TEXT NOT NULL,
	table_name TEXT NOT NULL,
	operation TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
	record_identity JSONB NOT NULL DEFAULT '{}'::jsonb,
	changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	jwt_subject TEXT,
	jwt_role TEXT,
	db_role TEXT NOT NULL DEFAULT CURRENT_USER,
	transaction_id BIGINT NOT NULL DEFAULT txid_current(),
	old_record JSONB,
	new_record JSONB
);

COMMENT ON TABLE private.row_change_audit IS 'Immutable row-level audit log used to recover from accidental destructive changes.';

CREATE INDEX IF NOT EXISTS idx_row_change_audit_table_changed_at
	ON private.row_change_audit (table_schema, table_name, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_row_change_audit_operation_changed_at
	ON private.row_change_audit (operation, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_row_change_audit_subject_changed_at
	ON private.row_change_audit (jwt_subject, changed_at DESC)
	WHERE jwt_subject IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_row_change_audit_record_identity
	ON private.row_change_audit
	USING GIN (record_identity jsonb_path_ops);

REVOKE ALL ON TABLE private.row_change_audit FROM PUBLIC;
REVOKE ALL ON TABLE private.row_change_audit FROM anon;
REVOKE ALL ON TABLE private.row_change_audit FROM authenticated;

CREATE OR REPLACE FUNCTION private.capture_row_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
	request_claims JSONB;
	previous_record JSONB;
	next_record JSONB;
	reference_record JSONB;
	record_identity JSONB;
BEGIN
	request_claims := COALESCE(NULLIF(current_setting('request.jwt.claims', true), ''), '{}')::jsonb;

	IF TG_OP = 'DELETE' THEN
		previous_record := to_jsonb(OLD);
		next_record := NULL;
		reference_record := previous_record;
	ELSIF TG_OP = 'UPDATE' THEN
		previous_record := to_jsonb(OLD);
		next_record := to_jsonb(NEW);
		reference_record := next_record;
	ELSE
		previous_record := NULL;
		next_record := to_jsonb(NEW);
		reference_record := next_record;
	END IF;

	record_identity := jsonb_strip_nulls(
		jsonb_build_object(
			'id', reference_record -> 'id',
			'cliente_id', reference_record -> 'cliente_id',
			'organization_id', reference_record -> 'organization_id',
			'folder_id', reference_record -> 'folder_id',
			'token_pre_consulta', reference_record -> 'token_pre_consulta',
			'slug', reference_record -> 'slug'
		)
	);

	INSERT INTO private.row_change_audit (
		table_schema,
		table_name,
		operation,
		record_identity,
		changed_at,
		jwt_subject,
		jwt_role,
		db_role,
		transaction_id,
		old_record,
		new_record
	)
	VALUES (
		TG_TABLE_SCHEMA,
		TG_TABLE_NAME,
		TG_OP,
		COALESCE(record_identity, '{}'::jsonb),
		NOW(),
		NULLIF(request_claims ->> 'sub', ''),
		COALESCE(NULLIF(request_claims ->> 'role', ''), CURRENT_USER),
		CURRENT_USER,
		txid_current(),
		previous_record,
		next_record
	);

	IF TG_OP = 'DELETE' THEN
		RETURN OLD;
	END IF;

	RETURN NEW;
END;
$$;

COMMENT ON FUNCTION private.capture_row_change() IS 'Captures before/after row snapshots for recovery from destructive mutations.';

REVOKE ALL ON FUNCTION private.capture_row_change() FROM PUBLIC;
REVOKE ALL ON FUNCTION private.capture_row_change() FROM anon;
REVOKE ALL ON FUNCTION private.capture_row_change() FROM authenticated;

DO $$
DECLARE
	qualified_table TEXT;
	table_schema TEXT;
	table_name TEXT;
	trigger_name TEXT;
BEGIN
	FOREACH qualified_table IN ARRAY ARRAY[
		'public.clientes',
		'public.diagnostico_capilar',
		'public.historico_procedimentos',
		'public.manutencao_homecare',
		'public.client_photos',
		'public.ficha_anamnese_capilar',
		'public.agendamentos',
		'public.pre_consulta_envios',
		'public.clinic_preferences',
		'public.company_document_folders',
		'public.company_documents',
		'public.organizations',
		'public.organization_members',
		'public.services'
	]
	LOOP
		IF to_regclass(qualified_table) IS NULL THEN
			CONTINUE;
		END IF;

		table_schema := split_part(qualified_table, '.', 1);
		table_name := split_part(qualified_table, '.', 2);
		trigger_name := format('trg_%s_capture_row_change', table_name);

		EXECUTE format(
			'DROP TRIGGER IF EXISTS %I ON %I.%I',
			trigger_name,
			table_schema,
			table_name
		);

		EXECUTE format(
			'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON %I.%I FOR EACH ROW EXECUTE FUNCTION private.capture_row_change()',
			trigger_name,
			table_schema,
			table_name
		);
	END LOOP;
END;
$$;
